language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

branches:
    only: master

env:
    global:
        - COMPOSER_PREFER_LOWEST=false
        - SYMFONY_DEPRECATIONS_HELPER=strict

install:
    - composer remove --no-update --dev friendsofphp/php-cs-fixer
    - composer update --prefer-source `if [ "$COMPOSER_PREFER_LOWEST" = true ]; then echo "--prefer-lowest --prefer-stable"; fi`

script: vendor/bin/phpunit --coverage-clover build/clover.xml

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml

matrix:
    include:
        - php: 5.6
          env: COMPOSER_PREFER_LOWEST=true
